[package]
name = "jindy500"
version = "0.1.0"
authors = ["Michael Mior <mmior@cs.rit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.11.14"
itertools = "0.10.3"
indicatif = "0.16.2"
