[package]
name = "jindy500"
version = "0.1.0"
authors = ["Michael Mior <mmior@cs.rit.edu>"]
edition = "2018"

[[bin]]
name = "jindy500-ind"
path = "src/ind.rs"

[[bin]]
name = "jindy500-fd"
path = "src/fd.rs"

[dependencies]
json = "0.12.4"
itertools = "0.10.3"
indicatif = "0.16.2"
roaring = { git = "https://github.com/michaelmior/roaring-rs", branch = "master" }
clap = { version = "3.2.22", features = ["derive"] }
rayon = "1.5.3"

[dev-dependencies]
rusty-hook = "0.11.2"
